package com.lonelyyhu.androidBeacon

object Constant {

    const val ACTION_START_FOREGROUND = "ACTION_START_FOREGROUND"
    const val ACTION_STOP_FOREGROUND = "ACTION_STOP_FOREGROUND"
    const val ACTION_START_SCAN = "ACTION_START_SCAN"
    const val ACTION_STOP_SCAN = "ACTION_STOP_SCAN"
    const val ACTION_SERVICE_START = "ACTION_SERVICE_START"

    val NOTIFICATION_ID_REGION_CHENGE = 100
    val NOTIFICATION_ID_FOREGROUND_SERVICE = 101

    const val NOTIFICATION_CHANNEL_ID = "NOTIFICATION_CHANNEL_ID"

}